# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

parameters:
- name: ServiceConnection
  type: string
  default: EphemeralEnvDeployment

- name: RegionName
  type: string
  default: us-east-2

- name: OnDemandTestEnv
  type: boolean
  default: false

trigger:
 branches:
    include:
    - main
    - releases/*
    - feature/*
    exclude:
    - releases/old*
    - feature/*-working

resources:
- repo: self
  repositories:
      - repository: cdk_pipelines
        type: git
        name: DevSecOps/cdk_pipelines

variables:
  - group: 'ephemeral_envrionments_demo'


stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: DevSecOpsEphemeralEnvironments
    steps:
#    - task: Docker@2
#      displayName: Build an image
#      inputs:
#        command: build
#        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
#        tags: |
#          '$(Build.BuildId)'
    - task: AWSShellScript@1
      inputs:
        awsCredentials: ${{ parameters.ServiceConnection }}
        regionName: ${{ parameters.RegionName }}
        scriptType: 'inline'
        inlineScript: |      
        
            echo Logging in to Amazon ECR...  $AWS_ACCOUNT_ID $AWS_DEFAULT_REGION 
            export TAG=$( git tag | tail -1)
            echo $TAG
            docker build -t complimentgeneralapi:$TAG .
            docker images
            echo complimentgeneralapi:$TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/complimentgeneralapi:$TAG
            docker tag complimentgeneralapi:$TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/complimentgeneralapi:$TAG
            docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-2.amazonaws.com/complimentgeneralapi:$TAG
            echo "##vso[task.setvariable variable=TAG;isOutput=true;]$TAG"
            #  aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com &
           

        displayName: 'ECRPush'
      env:
        AWS_ACCOUNT_ID: $(shared_account)
        AWS_DEFAULT_REGION:  $(shared_account_region)

- template: templates/ci_cd.yaml@cdk_pipelines  # Template reference
    
    parameters:
      Project: ephemeral_env_core
      Language: typescript
      Action: deploy
      ServiceConnection: EphemeralEnvDeployment
      CDKPath: infra
      OnDemandTestEnv: true
      Environment: test
      
      
    